#!/usr/bin/env bash

REPO_VISIBILITY=$(echo -e "private\npublic\ninternal" | fzf --layout=reverse --border --prompt="Select repo visibility: ")

if [ -z "$REPO_VISIBILITY" ]; then
  exit 0
fi

gh repo create "$@" --$REPO_VISIBILITY
ghq get $1
REPO_PATH=$(ghq list --full-path -e $1)

if [ -z "$REPO_PATH" ]; then
  exit 0
fi

cd $REPO_PATH
$EDITOR $REPO_PATH
